### ISSUE TITLE
How to get 64bit microsoft visual studio library?

### ISSUE THREAD

**Issue by kuh3h3** [ShiftMediaProject/speex#1]
there is no 64bit setting in the solution ,project files.

**Comment by Sibras** [comment]
Yes there is. The project contains 5 different configurations and 2 different architectures (x86 and x64). To choose 64bit just select x64 from the available architectures. If you don't know how to do this then you should look up Visual Studio help instructions.

**Comment by kuh3h3** [comment]
Why you not say this README? :)
i found special directory.
there is SMP direcotry i didn`t noticed.
but  no X64 option in ordinary place.

$ git clone  https://github.com/ShiftMediaProject/speex
'speex'에 복제합니다...
remote: Counting objects: 12031, done.
remote: Total 12031 (delta 0), reused 0 (delta 0), pack-reused 12031
오브젝트를 받는 중: 100% (12031/12031), 5.51 MiB | 64.00 KiB/s, 완료.
델타를 알아내는 중: 100% (9156/9156), 완료.
파일을 가져옵니다: 100% (274/274), 완료.

kuh3h3@DESKTOP-R0PM5LB MINGW64 ~
$ cd speex

kuh3h3@DESKTOP-R0PM5LB MINGW64 ~/speex
$ grep x64 *
grep: doc: Is a directory
grep: html: Is a directory
grep: include: Is a directory
grep: libspeex: Is a directory
grep: m4: Is a directory
grep: macosx: Is a directory
grep: SMP: Is a directory
grep: speexclient: Is a directory
grep: src: Is a directory
grep: symbian: Is a directory
grep: ti: Is a directory
grep: tmv: Is a directory
grep: win32: Is a directory

kuh3h3@DESKTOP-R0PM5LB MINGW64 ~/speex
$ grep x64 */*
doc/manual.lyx:- Excitation 5x64 (9600 bps)
grep: include/speex: Is a directory
grep: macosx/English.lproj: Is a directory
grep: macosx/Speex.xcodeproj: Is a directory
grep: macosx/Speex_UB.xcodeproj: Is a directory
SMP/appveyor.yml:platform: x86+x64
SMP/appveyor.yml:        <PlatformList Condition="'@(PlatformList)' == ''" Include="x64;x86" />
SMP/libspeex.sln:               Debug|x64 = Debug|x64
SMP/libspeex.sln:               DebugDLL|x64 = DebugDLL|x64
SMP/libspeex.sln:               Release|x64 = Release|x64
SMP/libspeex.sln:               ReleaseDLL|x64 = ReleaseDLL|x64
SMP/libspeex.sln:               ReleaseLTO|x64 = ReleaseLTO|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.Debug|x64.ActiveCfg = Debug|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.Debug|x64.Build.0 = Debug|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.DebugDLL|x64.ActiveCfg = DebugDLL|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.DebugDLL|x64.Build.0 = DebugDLL|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.Release|x64.ActiveCfg = Release|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.Release|x64.Build.0 = Release|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.ReleaseDLL|x64.ActiveCfg = ReleaseDLL|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.ReleaseDLL|x64.Build.0 = ReleaseDLL|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.ReleaseLTO|x64.ActiveCfg = ReleaseLTO|x64
SMP/libspeex.sln:               {564B2F86-5CDC-4D58-B869-5E8394CC3298}.ReleaseLTO|x64.Build.0 = ReleaseLTO|x64
SMP/libspeex.vcxproj:    <ProjectConfiguration Include="DebugDLL|x64">
SMP/libspeex.vcxproj:      <Platform>x64</Platform>
SMP/libspeex.vcxproj:    <ProjectConfiguration Include="Debug|x64">
SMP/libspeex.vcxproj:      <Platform>x64</Platform>
SMP/libspeex.vcxproj:    <ProjectConfiguration Include="ReleaseDLL|x64">
SMP/libspeex.vcxproj:      <Platform>x64</Platform>
SMP/libspeex.vcxproj:    <ProjectConfiguration Include="ReleaseLTO|x64">
SMP/libspeex.vcxproj:      <Platform>x64</Platform>
SMP/libspeex.vcxproj:    <ProjectConfiguration Include="Release|x64">
SMP/libspeex.vcxproj:      <Platform>x64</Platform>
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugDLL|x64'" Label="Configuration">
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseLTO|x64'" Label="Configuration">
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseDLL|x64'" Label="Configuration">
SMP/libspeex.vcxproj:  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="PropertySheets">
SMP/libspeex.vcxproj:  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='DebugDLL|x64'" Label="PropertySheets">
SMP/libspeex.vcxproj:  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="PropertySheets">
SMP/libspeex.vcxproj:  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseLTO|x64'" Label="PropertySheets">
SMP/libspeex.vcxproj:  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseDLL|x64'" Label="PropertySheets">
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugDLL|x64'">
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseLTO|x64'">
SMP/libspeex.vcxproj:  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseDLL|x64'">
SMP/libspeex.vcxproj:  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
SMP/libspeex.vcxproj:      <ProgramDataBaseFileName>$(OutDir)\lib\x64\$(TargetName).pdb</ProgramDataBaseFileName>
SMP/libspeex.vcxproj:      <OutputFile>$(OutDir)\lib\x64\$(TargetName)$(TargetExt)</OutputFile>
SMP/libspeex.vcxproj:  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='DebugDLL|x64'">
SMP/libspeex.vcxproj:      <OutputFile>$(OutDir)\bin\x64\$(TargetName)$(TargetExt)</OutputFile>
SMP/libspeex.vcxproj:      <ProgramDatabaseFile>$(OutDir)\lib\x64\$(TargetName).pdb</ProgramDatabaseFile>
SMP/libspeex.vcxproj:      <ImportLibrary>$(OutDir)\lib\x64\$(TargetName).lib</ImportLibrary>
SMP/libspeex.vcxproj:  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
SMP/libspeex.vcxproj:      <ProgramDataBaseFileName>$(OutDir)\lib\x64\$(TargetName).pdb</ProgramDataBaseFileName>
SMP/libspeex.vcxproj:      <OutputFile>$(OutDir)\lib\x64\$(TargetName)$(TargetExt)</OutputFile>
SMP/libspeex.vcxproj:  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseLTO|x64'">
SMP/libspeex.vcxproj:      <ProgramDataBaseFileName>$(OutDir)\lib\x64\$(TargetName).pdb</ProgramDataBaseFileName>
SMP/libspeex.vcxproj:      <OutputFile>$(OutDir)\lib\x64\$(TargetName)$(TargetExt)</OutputFile>
SMP/libspeex.vcxproj:  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseDLL|x64'">
SMP/libspeex.vcxproj:      <OutputFile>$(OutDir)\bin\x64\$(TargetName)$(TargetExt)</OutputFile>
SMP/libspeex.vcxproj:      <ProgramDatabaseFile>$(OutDir)\lib\x64\$(TargetName).pdb</ProgramDatabaseFile>
SMP/libspeex.vcxproj:      <ImportLibrary>$(OutDir)\lib\x64\$(TargetName).lib</ImportLibrary>
grep: ti/speex_C54_test: Is a directory
grep: ti/speex_C55_test: Is a directory
grep: ti/speex_C64_test: Is a directory
grep: win32/libspeex: Is a directory
grep: win32/speexdec: Is a directory
grep: win32/speexenc: Is a directory
grep: win32/VS2003: Is a directory
grep: win32/VS2005: Is a directory
grep: win32/VS2008: Is a directory

kuh3h3@DESKTOP-R0PM5LB MINGW64 ~/speex
$ grep x64 */*/*
grep: win32/VS2003/libspeex: Is a directory
grep: win32/VS2003/speexdec: Is a directory
grep: win32/VS2003/speexenc: Is a directory
grep: win32/VS2003/tests: Is a directory
grep: win32/VS2005/libspeex: Is a directory
grep: win32/VS2005/speexdec: Is a directory
grep: win32/VS2005/speexenc: Is a directory
grep: win32/VS2005/tests: Is a directory
grep: win32/VS2008/libspeex: Is a directory
grep: win32/VS2008/speexdec: Is a directory
grep: win32/VS2008/speexenc: Is a directory
grep: win32/VS2008/tests: Is a directory

kuh3h3@DESKTOP-R0PM5LB MINGW64 ~/speex
$ grep x64 */*/*/*

kuh3h3@DESKTOP-R0PM5LB MINGW64 ~/speex
$ grep x64 */*/*/*/*
grep: */*/*/*/*: No such file or directory
